version: "3.1"
services:
  bot:
    image: oreonite-manganese
    working_dir: /usr/es-discord-oreonitemanganese
    volumes:
      - ./:/usr/es-discord-oreonitemanganese
      - /usr/es-discord-oreonitemanganese/node_modules
    ports:
      - 2222:8080
    command: "npm run start"