version: "3.1"
services:
  bot:
    image: oreonite-manganese
    user: "node"
    working_dir: /var/www/es-discord-oreonitemanganese
    volumes:
      - ./:/var/www/es-discord-oreonitemanganese
    ports:
      - 2222:8080